GET http://127.0.0.1:3000/api/users/

GET http://127.0.0.1:3000/api/users/6620d6910101788d2c6648df

POST http://127.0.0.1:3000/api/users/
Content-Type: application/json

{
    "name": "Jackie Chan",
    "email": "jackie@chan.fr",
    "password": "password"
}

PUT http://127.0.0.1:3000/api/users/6620d6910101788d2c6648df
Content-Type: application/json

{
    "password": "motdepasse"
}

DELETE http://127.0.0.1:3000/api/users/6620d6910101788d2c6648df