###
GET http://localhost:3000/api/club

###
GET http://localhost:3000/api/club/1

###
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name": "Romain",
    "email": "romain19@gmail.com",
    "password": "password"
} 


###
POST http://localhost:3000/api/user/login
Content-Type: application/json

{ 
    "email": "test@example.com",
    "password": "motdepasse123"
}

###
GET http://127.0.0.1:3000/api/user/

###
GET http://127.0.0.1:3000/api/user/6620d6910101788d2c6648df

###
PUT http://127.0.0.1:3000/api/user/6620d6910101788d2c6648df
Content-Type: application/json

{
    "password": "motdepasse"
}

###
DELETE http://127.0.0.1:3000/api/user/6620d6910101788d2c6648df

###
GET http://127.0.0.1:3000/api/player?available=true&page=2