export interface Player {
    id: number,
    firstName: string,
    lastName: string,
    name: string,
    height: number,
    weight: number,
    gender: string,
    birthDate: Date,
    age: number,
    league: number,
    nation: number,
    club: number,
    rarity: number,
    position: string,
    skillMoves: number,
    weakFoot: number,
    foot: string,
    attackWorkRate: string,
    defenseWorkRate: string,
    totalStats: number,
    totalStatsInGame: number,
    color: string,
    rating: number,
    ratingAverage: number,
    available: boolean
}
